/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewEditor.java
 *
 * Created on 1 nov. 2010, 10:16:17
 */
package net.vpc.gaming.atom.tools.mapeditor;

import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.IOException;

/**
 * @author Taha Ben Salah (taha.bensalah@gmail.com)
 */
public class NewEditor extends javax.swing.JPanel {

    /**
     * Creates new form NewEditor
     */
    public NewEditor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        imageColumnsField = new javax.swing.JTextField();
        imageRowsField = new javax.swing.JTextField();
        tilesPerCellColumnField = new javax.swing.JTextField();
        tilesPerCellRowField = new javax.swing.JTextField();
        mapColumnsField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        mapRowsField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        projectFileField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        imageFileField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        jLabel2.setText("Cell");

        jLabel5.setText("splitted by");

        imageColumnsField.setText("jTextField2");

        imageRowsField.setText("jTextField3");

        tilesPerCellColumnField.setText("jTextField4");

        tilesPerCellRowField.setText("jTextField5");

        mapColumnsField.setText("jTextField1");

        jLabel6.setText("Map");

        mapRowsField.setText("jTextField2");

        jLabel1.setText("Project File");

        projectFileField.setText("jTextField1");

        jLabel9.setText("Images from");

        imageFileField.setText("jTextField3");

        jButton1.setText("...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("...");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel8.setText("x");

        jLabel10.setText("Cells");

        jLabel11.setText("=");

        jLabel12.setText("=");

        jLabel13.setText("x");

        jLabel14.setText("Tiles");

        jLabel16.setText("x");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel6)
                                                        .addComponent(jLabel2)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(77, 77, 77)
                                                                .addComponent(jLabel5))
                                                        .addComponent(jLabel1))
                                                .addGap(9, 9, 9)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(21, 21, 21)
                                                                .addComponent(imageColumnsField)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jLabel16)
                                                                .addGap(4, 4, 4)
                                                                .addComponent(imageRowsField, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(116, 116, 116))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                        .addComponent(jLabel11)
                                                                                        .addComponent(jLabel12))
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                        .addComponent(tilesPerCellColumnField, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                                                                                        .addComponent(mapColumnsField))
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(jLabel8)
                                                                                        .addComponent(jLabel13))
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                        .addComponent(mapRowsField, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                                                                        .addComponent(tilesPerCellRowField))
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(jLabel10)
                                                                                        .addComponent(jLabel14)))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(projectFileField, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jButton1))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(imageFileField, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jButton2)))
                                                                .addGap(22, 37, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(projectFileField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(mapColumnsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(mapRowsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel14)
                                        .addComponent(tilesPerCellColumnField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tilesPerCellRowField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel9)
                                        .addComponent(imageFileField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(imageRowsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel16)
                                                .addComponent(imageColumnsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser c = new JFileChooser();
        c.setFileSelectionMode(JFileChooser.FILES_ONLY);
        c.addChoosableFileFilter(new FileNameExtensionFilter("map project file", "mpj"));
        c.setSelectedFile(null);
        int r = c.showSaveDialog(null);
        if (r == JFileChooser.APPROVE_OPTION) {
            try {
                projectFileField.setText(c.getSelectedFile().getCanonicalPath());
            } catch (IOException ex) {
                projectFileField.setText(c.getSelectedFile().getAbsolutePath());
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JFileChooser c = new JFileChooser();
        c.setFileSelectionMode(JFileChooser.FILES_ONLY);
        c.addChoosableFileFilter(new FileNameExtensionFilter("map file", "map"));
        c.setSelectedFile(null);
        int r = c.showSaveDialog(null);
        if (r == JFileChooser.APPROVE_OPTION) {
            try {
                imageFileField.setText(c.getSelectedFile().getCanonicalPath());
            } catch (IOException ex) {
                imageFileField.setText(c.getSelectedFile().getAbsolutePath());
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField imageColumnsField;
    private javax.swing.JTextField imageFileField;
    private javax.swing.JTextField imageRowsField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField mapColumnsField;
    private javax.swing.JTextField mapRowsField;
    private javax.swing.JTextField projectFileField;
    private javax.swing.JTextField tilesPerCellColumnField;
    private javax.swing.JTextField tilesPerCellRowField;
    // End of variables declaration//GEN-END:variables

    public void clear() {
        imageColumnsField.setText("");
        imageRowsField.setText("");
        tilesPerCellColumnField.setText("");
        tilesPerCellRowField.setText("");
        mapColumnsField.setText("");
        mapRowsField.setText("");
        imageFileField.setText("");
        projectFileField.setText("");
    }

    public JButton getProjectFileButton() {
        return jButton1;
    }

    public javax.swing.JTextField getProjectFileField() {
        return projectFileField;
    }

    public String getImageFile() {
        return imageFileField.getText();
    }

    public String getProjectFile() {
        return projectFileField.getText();
    }

    public void setProjectFile(String s) {
        projectFileField.setText(s);
    }

    public void setImageFile(String s) {
        imageFileField.setText(s);
    }

    public void setImageColumns(int v) {
        imageColumnsField.setText(String.valueOf(v));
    }

    public int getImageColumns() {
        return getInt(imageColumnsField.getText());
    }

    public void setImageRows(int v) {
        imageRowsField.setText(String.valueOf(v));
    }

    public int getImageRows() {
        return getInt(imageRowsField.getText());
    }

    public void setTileRowsPerCell(int v) {
        tilesPerCellRowField.setText(String.valueOf(v));
    }

    public int getTileRowsPerCell() {
        return getInt(tilesPerCellRowField.getText());
    }

    public void setTileColumnsPerCell(int v) {
        tilesPerCellColumnField.setText(String.valueOf(v));
    }

    public int getTileColumnsPerCell() {
        return getInt(tilesPerCellColumnField.getText());
    }

    public void setMapColumns(int v) {
        mapColumnsField.setText(String.valueOf(v));
    }

    public int getMapColumns() {
        return getInt(mapColumnsField.getText());
    }

    public int getMapRows() {
        return getInt(mapRowsField.getText());
    }

    public void setMapRows(int v) {
        mapRowsField.setText(String.valueOf(v));
    }

    private int getInt(String s) {
        try {
            return Integer.parseInt(s);
        } catch (Exception e) {
            return 0;
        }
    }
}
