package jcanon;


/**
* jcanon/CorbaGameStatus.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/vpc/xprojects/games/canon/src/tn/rnu/enit/ateliercorba/jcanon/jcanon.idl
* lundi 15 octobre 2007 19 h 43 CEST
*/

public class CorbaGameStatus implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 3;
  private static jcanon.CorbaGameStatus[] __array = new jcanon.CorbaGameStatus [__size];

  public static final int _GAME_INIT = 0;
  public static final jcanon.CorbaGameStatus GAME_INIT = new jcanon.CorbaGameStatus(_GAME_INIT);
  public static final int _GAME_STARTED = 1;
  public static final jcanon.CorbaGameStatus GAME_STARTED = new jcanon.CorbaGameStatus(_GAME_STARTED);
  public static final int _GAME_OVER = 2;
  public static final jcanon.CorbaGameStatus GAME_OVER = new jcanon.CorbaGameStatus(_GAME_OVER);

  public int value ()
  {
    return __value;
  }

  public static jcanon.CorbaGameStatus from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected CorbaGameStatus (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class CorbaGameStatus
