package jcanon;

/**
* jcanon/CorbaPlaneBombTypeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/vpc/xprojects/gaming/canon/src/tn/rnu/enit/ateliercorba/jcanon/jcanon.idl
* lundi 15 octobre 2007 19 h 43 CEST
*/

public final class CorbaPlaneBombTypeHolder implements org.omg.CORBA.portable.Streamable
{
  public jcanon.CorbaPlaneBombType value = null;

  public CorbaPlaneBombTypeHolder ()
  {
  }

  public CorbaPlaneBombTypeHolder (jcanon.CorbaPlaneBombType initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = jcanon.CorbaPlaneBombTypeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    jcanon.CorbaPlaneBombTypeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return jcanon.CorbaPlaneBombTypeHelper.type ();
  }

}
