package jcanon;


/**
* jcanon/CorbaGameHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/vpc/xprojects/games/canon/src/tn/rnu/enit/ateliercorba/jcanon/jcanon.idl
* lundi 15 octobre 2007 19 h 43 CEST
*/

abstract public class CorbaGameHelper
{
  private static String  _id = "IDL:tn.rnu.enit.ateliercorba/jcanon/CorbaGame/CorbaGame:1.0";

  public static void insert (org.omg.CORBA.Any a, jcanon.CorbaGame that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static jcanon.CorbaGame extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [5];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = jcanon.CorbaGameStatusHelper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "gameStatus",
            _tcOf_members0,
            null);
          _tcOf_members0 = jcanon.CorbaCanonHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "canons",
            _tcOf_members0,
            null);
          _tcOf_members0 = jcanon.CorbaPlaneHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "planes",
            _tcOf_members0,
            null);
          _tcOf_members0 = jcanon.CorbaFireHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "fires",
            _tcOf_members0,
            null);
          _tcOf_members0 = jcanon.CorbaPlaneBombHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _members0[4] = new org.omg.CORBA.StructMember (
            "bombs",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (jcanon.CorbaGameHelper.id (), "CorbaGame", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static jcanon.CorbaGame read (org.omg.CORBA.portable.InputStream istream)
  {
    jcanon.CorbaGame value = new jcanon.CorbaGame ();
    value.gameStatus = jcanon.CorbaGameStatusHelper.read (istream);
    int _len0 = istream.read_long ();
    value.canons = new jcanon.CorbaCanon[_len0];
    for (int _o1 = 0;_o1 < value.canons.length; ++_o1)
      value.canons[_o1] = jcanon.CorbaCanonHelper.read (istream);
    int _len1 = istream.read_long ();
    value.planes = new jcanon.CorbaPlane[_len1];
    for (int _o2 = 0;_o2 < value.planes.length; ++_o2)
      value.planes[_o2] = jcanon.CorbaPlaneHelper.read (istream);
    int _len2 = istream.read_long ();
    value.fires = new jcanon.CorbaFire[_len2];
    for (int _o3 = 0;_o3 < value.fires.length; ++_o3)
      value.fires[_o3] = jcanon.CorbaFireHelper.read (istream);
    int _len3 = istream.read_long ();
    value.bombs = new jcanon.CorbaPlaneBomb[_len3];
    for (int _o4 = 0;_o4 < value.bombs.length; ++_o4)
      value.bombs[_o4] = jcanon.CorbaPlaneBombHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, jcanon.CorbaGame value)
  {
    jcanon.CorbaGameStatusHelper.write (ostream, value.gameStatus);
    ostream.write_long (value.canons.length);
    for (int _i0 = 0;_i0 < value.canons.length; ++_i0)
      jcanon.CorbaCanonHelper.write (ostream, value.canons[_i0]);
    ostream.write_long (value.planes.length);
    for (int _i1 = 0;_i1 < value.planes.length; ++_i1)
      jcanon.CorbaPlaneHelper.write (ostream, value.planes[_i1]);
    ostream.write_long (value.fires.length);
    for (int _i2 = 0;_i2 < value.fires.length; ++_i2)
      jcanon.CorbaFireHelper.write (ostream, value.fires[_i2]);
    ostream.write_long (value.bombs.length);
    for (int _i3 = 0;_i3 < value.bombs.length; ++_i3)
      jcanon.CorbaPlaneBombHelper.write (ostream, value.bombs[_i3]);
  }

}
