package jcanon;

/**
* jcanon/CorbaPlaneStatusHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/vpc/xprojects/games/canon/src/tn/rnu/enit/ateliercorba/jcanon/jcanon.idl
* lundi 15 octobre 2007 19 h 43 CEST
*/

public final class CorbaPlaneStatusHolder implements org.omg.CORBA.portable.Streamable
{
  public jcanon.CorbaPlaneStatus value = null;

  public CorbaPlaneStatusHolder ()
  {
  }

  public CorbaPlaneStatusHolder (jcanon.CorbaPlaneStatus initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = jcanon.CorbaPlaneStatusHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    jcanon.CorbaPlaneStatusHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return jcanon.CorbaPlaneStatusHelper.type ();
  }

}
