package jcanon;


/**
* jcanon/CorbaPlane.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/vpc/xprojects/gaming/canon/src/tn/rnu/enit/ateliercorba/jcanon/jcanon.idl
* lundi 15 octobre 2007 19 h 43 CEST
*/

public final class CorbaPlane implements org.omg.CORBA.portable.IDLEntity
{
  public int x = (int)0;
  public int y = (int)0;
  public jcanon.CorbaPlaneType type = null;
  public jcanon.CorbaPlaneStatus status = null;
  public int mood = (int)0;

  public CorbaPlane ()
  {
  } // ctor

  public CorbaPlane (int _x, int _y, jcanon.CorbaPlaneType _type, jcanon.CorbaPlaneStatus _status, int _mood)
  {
    x = _x;
    y = _y;
    type = _type;
    status = _status;
    mood = _mood;
  } // ctor

} // class CorbaPlane
