package jcanon;


/**
* jcanon/CorbaPlaneBomb.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/vpc/xprojects/gaming/canon/src/tn/rnu/enit/ateliercorba/jcanon/jcanon.idl
* lundi 15 octobre 2007 19 h 43 CEST
*/

public final class CorbaPlaneBomb implements org.omg.CORBA.portable.IDLEntity
{
  public int x = (int)0;
  public int y = (int)0;
  public jcanon.CorbaPlaneBombType type = null;
  public int mood = (int)0;

  public CorbaPlaneBomb ()
  {
  } // ctor

  public CorbaPlaneBomb (int _x, int _y, jcanon.CorbaPlaneBombType _type, int _mood)
  {
    x = _x;
    y = _y;
    type = _type;
    mood = _mood;
  } // ctor

} // class CorbaPlaneBomb
