package jcanon;


/**
* jcanon/CorbaGame.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/vpc/xprojects/games/canon/src/tn/rnu/enit/ateliercorba/jcanon/jcanon.idl
* lundi 15 octobre 2007 19 h 43 CEST
*/

public final class CorbaGame implements org.omg.CORBA.portable.IDLEntity
{
  public jcanon.CorbaGameStatus gameStatus = null;
  public jcanon.CorbaCanon canons[] = null;
  public jcanon.CorbaPlane planes[] = null;
  public jcanon.CorbaFire fires[] = null;
  public jcanon.CorbaPlaneBomb bombs[] = null;

  public CorbaGame ()
  {
  } // ctor

  public CorbaGame (jcanon.CorbaGameStatus _gameStatus, jcanon.CorbaCanon[] _canons, jcanon.CorbaPlane[] _planes, jcanon.CorbaFire[] _fires, jcanon.CorbaPlaneBomb[] _bombs)
  {
    gameStatus = _gameStatus;
    canons = _canons;
    planes = _planes;
    fires = _fires;
    bombs = _bombs;
  } // ctor

} // class CorbaGame
