package jcanon;


/**
* jcanon/JCanonClientOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/vpc/xprojects/gaming/canon/src/tn/rnu/enit/ateliercorba/jcanon/jcanon.idl
* lundi 15 octobre 2007 19 h 43 CEST
*/

public interface JCanonClientOperations 
{
  void modelChanged (jcanon.CorbaGame model);
} // interface JCanonClientOperations
