package jcanon;


/**
* jcanon/JCanonServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/vpc/xprojects/games/canon/src/tn/rnu/enit/ateliercorba/jcanon/jcanon.idl
* lundi 15 octobre 2007 19 h 43 CEST
*/

public interface JCanonServerOperations 
{
  int connect (jcanon.JCanonClient client);
  void playerHitFire (int player);
  void playerMoveLeft (int player);
  void playerMoveRight (int player);
} // interface JCanonServerOperations
